
import Image from "next/image";
import "./globals.css";
import { Navbar } from "./components/Navbar";
import { Footer } from "./components/Footer";
import { Irish_Grover } from "next/font/google";
import type { Metadata } from "next";

// EXAMPLE FONT IMPORTS
const irish = Irish_Grover({
  variable: "--font-irish",
  subsets: ["latin"],
  weight: "400",
});

// GLOBALS METADATA
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fr">
      <body className={`${irish.variable} flex flex-col min-h-screen antialiased`}>
        
      <header className="absolute top-0 left-0 w-full z-20">
        <Navbar />
      </header>

        <div className="absolute top-0 left-0 w-full h-full -z-10">
          <Image
            src="https://live.staticflickr.com/65535/54461185237_bfd62aa372_b.jpg"
            alt="Background"
            className="object-cover"
            fill
            priority
          />
          <div className="relative h-full w-full overflow-hidden">
            <Image
              id="rocket"
              src="/fusee.png"
              alt=""
              width={80}
              height={80}
              className="absolute bottom-20 right-100"
            />
          </div>
        </div>

        <div className="absolute top-0 left-0 w-full h-full bg-black opacity-[25%] -z-10"></div>

        <main className="relative z-10 flex-grow">{children}</main>

        <footer className="relative z-10 mt-auto">
          <Footer />
        </footer>
      </body>
    </html>
  );
}
